name: release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/azwi
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v6

      - uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.13"
          enable-cache: false

      - name: Build
        run: uv build --no-sources

      - name: Publish
        run: uv publish
